txt_box_usrname = '//*[@id="user-name"]'
txt_box_password = '//*[@id="password"]'
btn_login = '//*[@id="login-button"]'
lnk_backpack = '//div[contains(text(), <product_name>)]'
txt_products = '//span[contains(text(), "Products")]'
btn_add_cart = '//*[ contains(@id, "add-to-cart")]'
btn_remove = '//*[ contains(@id, "remove")]'
shopping_cart_btn = '//span[@class="shopping_cart_badge"]'
btn_checkout = '//*[@id="checkout"]'
txt_box_firstname = '//*[@id="first-name"]'
txt_box_lastname = '//*[@id="last-name"]'
txt_box_zipcode = '//*[@id="postal-code"]'
btn_finish = '//*[@id="finish"]'
btn_continue = '//*[@id="continue"]'
txt_payment_info = '//div[contains(text(), "Payment Information")]'
txt_shipping_info = '//div[contains(text(), "Shipping Information")]'
txt_thank_you = '//h2[contains(text(), "Thank you for")]'
btn_back_home = '//*[@id="back-to-products"]'